# Path to your oh-my-zsh configuration.
export ZSH=$HOME/dotfiles/zsh/oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="prose"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git svn vi-mode osx)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...

source ~/dotfiles/bash/env
source ~/dotfiles/bash/aliases
source ~/dotfiles/bash/shellscripts

# Set Vi-like binding
bindkey -v

echo  "$fg[red]Today is:\t\t $fg[cyan]`date`"
echo  "$fg[red]Kernel Information:\t $fg[cyan]`uname -smr` " 
echo  "$fg[green]$(box_name) $fg[red]uptime is:\t $fg[cyan]`uptime | awk /'up/ {print $3,$4,$5,$6,$7,$8,$9,$10}'`$reset_color"
echo ""
fortune
echo ""
echo ""
echo "$fg[red] *** System Message ***"
echo "$fg_bold[green]`cat /etc/motd`"
echo ""
# RVM integration
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
