#!/bin/bash

#------------------------------------------////
# Basic:
#------------------------------------------////
#alias ls='ls -G' 
#alias la='ls -laGh'
alias ls='ls --color=auto'
alias la='ls --color=auto -lah'
alias findbig='find . -type f -exec ls -s {} \; | sort -n -r | head -5'
alias cls='clear'
alias ..='cd ..'
alias cdd='cd -'
alias grep='grep --color=auto'
alias diff='colordiff'
alias more='less'
alias df='df -h'
alias du='du -c -h'
alias mkdir='mkdir -p -v'
alias tmux='tmux -2'

#------------------------------------------////
# Only for Mac OSX
#------------------------------------------////
alias brewupd='brew update && brew list | xargs brew install'

#------------------------------------------////
# Network
#------------------------------------------////
alias ping='ping -c 4'

#------------------------------------------////
# Version Control:
#------------------------------------------////
## GIT
alias gst='git status --ignore-submodules'
alias gl='git pull'
alias gp='git push'
alias gd='git diff | mate'
alias gc='git commit -v'
alias gca='git commit -v -a'
alias gb='git branch'
alias gba='git branch -a'
